### ISSUE TITLE
V 11.* contains bugs

### ISSUE THREAD

**Issue by madrigal1** [madrigal1/ConvoAppDPS#2]
semicolon missing
To be fixed in v 12

**Comment by madrigal1** [comment]
Download v 10 for stable temp demo of project if needed

**Comment by madrigal1** [comment]
May be fixed by using a cross commit manual compare
  Working from v10 o v11 manually may be able to fjx it

**Comment by InfantDerrick** [comment]
Does this only work with turbocpp or can i use any IDE?

**Comment by madrigal1** [comment]
Update 12.0 fixes issues with a cross commit debug and  adoption of more convectional file io methods
